id: IEDE80AD0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-14T10:51:07+00:00'
last_modified: '2022-06-10T04:50:25.820438+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29982
  title: མན་ངག་རྒྱུད་དང་ཕྱི་མ་རྒྱུད་ཀྱི་ལྷན་ཐབས་ཀྱི་ཚུལ་དུ་བཀོད་པ་ཕན་བདེའི་ནོར་བུའི་བང་མཛོད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EEAE:
      image_group_id: I1PD384
      title: Volume 1 of man ngag rgyud dang phyi ma rgyud kyi lhan thabs kyi tshul
        du bkod pa phan bde'i nor bu'i bang mdzod
      total_pages: 974
      order: 1
      base_file: EEAE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
